import Head from "next/head";

import { Box, Center, Heading } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mightymeld Next Chakra Starter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box position="relative" h="100px">
          <Center p="20">
            <Heading> Mightymeld-Next-Chakra Starter</Heading>
          </Center>
        </Box>
      </main>
    </>
  );
}
